 @port = 3000

### GET - Methods

// GET - Working
### GET http://localhost:{{port}}/api/menu

// GET by ID - Working
### GET http://localhost:{{port}}/api/menu/662ebfaf560f3b2cc469888e

### POST - Methods - Working

// POST - MENU

### POST http://localhost:{{port}}/api/menu

//POST - EVENTS

### POST http://localhost:{{port}}/api/events


// UPDATE - Working On

### Insert HERE For Testing

// UPDATE BY ID?

### Insert HERE For Testing

// DELETE - Works

### DELETE http://localhost:{{port}}/api/menu/:id

