
    @id = 662ebed8b933068f3a44e389
    @port = 3000

### GET - Methods


//GET http://localhost:{{port}}/api/menu
//

//Get

//GET http://localhost:{{port}}/api/events

// GET by ID - Working 

GET http://localhost:{{port}}/api/menu/66381f3d86fe5ec6b8e609ba

### POST - Methods

// POST - MENU
POST http://localhost:{{port}}/api/menu
Content-Type: application/json

{
  "name":"test2",
  "description":"test2",
  "price":"test2"
}

### Insert HERE For Testing

// UPDATE / PUT HERE

### Insert HERE For Testing

// UPDATE BY ID?

### Insert HERE For Testing

PUT http://localhost:{{port}}/api/menu/{{id}}
Content-Type: application/json

// DELETE - Works

### DELETE http://localhost:{{port}}/api/menu/:id



    @port = 3000

### GET - Methods

// GET - Working ### GET http://localhost:{{port}}/api/menu

// GET by ID - Working ### 
//GET http://localhost:{{port}}/api/menu/66381f3d86fe5ec6b8e609ba

### POST - Methods - Working

// POST - MENU

    ###POST http://localhost:{{port}}/api/menu

//POST - EVENTS

    ### POST http://localhost:{{port}}/api/events

// UPDATE - Working On

PUT http://localhost:{{port}}/api/events/66397a4f147ce085f9316761

// UPDATE BY ID?

### Insert HERE For Testing

// DELETE - Works

### DELETE http://localhost:{{port}}/api/menu/:id
